sonar.projectKey=wonwon0307_wondocs
sonar.organization=wonwon0307

sonar.sources=configs,packages

sonar.typescript.tsconfigPaths=**/*/tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/*.*
sonar.cpd.exclusions=**/tests/**
